# Generated by Django 4.2.16 on 2025-10-06 13:44

from decimal import Decimal
from django.conf import settings
import django.contrib.auth.models
import django.contrib.auth.validators
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                (
                    "username",
                    models.CharField(
                        error_messages={
                            "unique": "A user with that username already exists."
                        },
                        help_text="Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.",
                        max_length=150,
                        unique=True,
                        validators=[
                            django.contrib.auth.validators.UnicodeUsernameValidator()
                        ],
                        verbose_name="username",
                    ),
                ),
                (
                    "first_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="first name"
                    ),
                ),
                (
                    "last_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="last name"
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True, max_length=254, verbose_name="email address"
                    ),
                ),
                (
                    "is_staff",
                    models.BooleanField(
                        default=False,
                        help_text="Designates whether the user can log into this admin site.",
                        verbose_name="staff status",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Designates whether this user should be treated as active. Unselect this instead of deleting accounts.",
                        verbose_name="active",
                    ),
                ),
                (
                    "date_joined",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="date joined"
                    ),
                ),
                ("clue", models.CharField(blank=True, max_length=50, null=True)),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific permissions for this user.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.permission",
                        verbose_name="user permissions",
                    ),
                ),
            ],
            options={
                "verbose_name": "user",
                "verbose_name_plural": "users",
                "abstract": False,
            },
            managers=[
                ("objects", django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name="Alcaldia",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=100, unique=True)),
                (
                    "codigo",
                    models.CharField(blank=True, max_length=10, null=True, unique=True),
                ),
                ("activo", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "Alcaldía",
                "verbose_name_plural": "Alcaldías",
                "ordering": ["nombre"],
            },
        ),
        migrations.CreateModel(
            name="CategoriaProducto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=100, unique=True)),
                ("descripcion", models.TextField(blank=True, null=True)),
                (
                    "codigo",
                    models.CharField(blank=True, max_length=20, null=True, unique=True),
                ),
            ],
            options={
                "verbose_name": "Categoría de Producto",
                "verbose_name_plural": "Categorías de Productos",
                "ordering": ["nombre"],
            },
        ),
        migrations.CreateModel(
            name="EstadoInsumo",
            fields=[
                (
                    "id_estado",
                    models.PositiveSmallIntegerField(
                        choices=[
                            (1, "Disponible"),
                            (4, "Suspendido"),
                            (5, "Deteriorado"),
                            (6, "Caducado"),
                        ],
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("descripcion", models.CharField(editable=False, max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name="FuenteFinanciamiento",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=100, unique=True)),
                ("descripcion", models.TextField(blank=True, null=True)),
                (
                    "codigo",
                    models.CharField(blank=True, max_length=20, null=True, unique=True),
                ),
            ],
            options={
                "verbose_name": "Fuente de Financiamiento",
                "verbose_name_plural": "Fuentes de Financiamiento",
                "ordering": ["nombre"],
            },
        ),
        migrations.CreateModel(
            name="Institucion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "clue",
                    models.CharField(max_length=20, unique=True, verbose_name="CLUE"),
                ),
                (
                    "ib_clue",
                    models.CharField(
                        blank=True,
                        max_length=20,
                        null=True,
                        unique=True,
                        verbose_name="IB CLUE",
                    ),
                ),
                (
                    "denominacion",
                    models.CharField(max_length=200, verbose_name="Denominación"),
                ),
                (
                    "estado",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="Estado"
                    ),
                ),
                (
                    "municipio",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="Municipio"
                    ),
                ),
                (
                    "nombre",
                    models.CharField(
                        blank=True,
                        max_length=200,
                        null=True,
                        verbose_name="Nombre de la institución",
                    ),
                ),
                ("direccion", models.TextField(blank=True, null=True)),
                ("telefono", models.CharField(blank=True, max_length=20, null=True)),
                ("email", models.EmailField(blank=True, max_length=254, null=True)),
                ("activo", models.BooleanField(default=True)),
                ("fecha_creacion", models.DateTimeField(auto_now_add=True)),
                ("fecha_actualizacion", models.DateTimeField(auto_now=True)),
                (
                    "alcaldia",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="inventario.alcaldia",
                    ),
                ),
            ],
            options={
                "verbose_name": "Institución",
                "verbose_name_plural": "Instituciones",
                "ordering": ["denominacion"],
            },
        ),
        migrations.CreateModel(
            name="Lote",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("numero_lote", models.CharField(max_length=50)),
                ("observaciones", models.TextField(blank=True, null=True)),
                (
                    "cantidad_inicial",
                    models.PositiveIntegerField(verbose_name="Cantidad Inicial"),
                ),
                (
                    "cantidad_disponible",
                    models.PositiveIntegerField(verbose_name="Cantidad Disponible"),
                ),
                (
                    "precio_unitario",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.01"))
                        ],
                    ),
                ),
                (
                    "valor_total",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=12,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.01"))
                        ],
                    ),
                ),
                ("fecha_fabricacion", models.DateField()),
                ("fecha_caducidad", models.DateField()),
                ("fecha_recepcion", models.DateField()),
                (
                    "estado",
                    models.IntegerField(
                        choices=[
                            (1, "Disponible"),
                            (4, "Suspendido"),
                            (5, "Deteriorado"),
                            (6, "Caducado"),
                        ],
                        default=1,
                    ),
                ),
                ("motivo_cambio_estado", models.TextField(blank=True, null=True)),
                ("fecha_cambio_estado", models.DateTimeField(blank=True, null=True)),
                (
                    "uuid",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("fecha_creacion", models.DateTimeField(auto_now_add=True)),
                ("fecha_actualizacion", models.DateTimeField(auto_now=True)),
                (
                    "creado_por",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="lotes_creados",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "institucion",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="inventario.institucion",
                    ),
                ),
            ],
            options={
                "verbose_name": "Lote",
                "verbose_name_plural": "Lotes",
                "ordering": ["-fecha_recepcion", "fecha_caducidad"],
            },
        ),
        migrations.CreateModel(
            name="Proveedor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "rfc",
                    models.CharField(max_length=13, unique=True, verbose_name="RFC"),
                ),
                (
                    "razon_social",
                    models.CharField(max_length=200, verbose_name="Razón Social"),
                ),
                ("direccion", models.TextField(blank=True, null=True)),
                ("telefono", models.CharField(blank=True, max_length=20, null=True)),
                ("email", models.EmailField(blank=True, max_length=254, null=True)),
                (
                    "contacto_principal",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("activo", models.BooleanField(default=True)),
                ("fecha_creacion", models.DateTimeField(auto_now_add=True)),
                ("fecha_actualizacion", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Proveedor",
                "verbose_name_plural": "Proveedores",
                "ordering": ["razon_social"],
            },
        ),
        migrations.CreateModel(
            name="TipoInstitucion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("HOSPITAL_PEDIATRICO", "Hospital Pediátrico"),
                            ("HOSPITAL_MATERNO_INFANTIL", "Hospital Materno Infantil"),
                            ("HOSPITAL_GENERAL", "Hospital General"),
                            ("CENTRO_SALUD_T1", "Centro de Salud T-I"),
                            ("CENTRO_SALUD_T2", "Centro de Salud T-II"),
                            ("CENTRO_SALUD_T3", "Centro de Salud T-III"),
                            ("OTRO", "Otro"),
                        ],
                        max_length=50,
                        unique=True,
                    ),
                ),
                ("descripcion", models.TextField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "Tipo de Institución",
                "verbose_name_plural": "Tipos de Instituciones",
                "ordering": ["tipo"],
            },
        ),
        migrations.CreateModel(
            name="SolicitudInventario",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fecha_generacion", models.DateField(auto_now_add=True)),
                ("entidad_federativa", models.CharField(max_length=100)),
                ("clues", models.CharField(max_length=20)),
                (
                    "orden_suministro",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "rfc_proveedor",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                (
                    "fuente_financiamiento",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "partida_presupuestal",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("concatenar", models.CharField(blank=True, max_length=100, null=True)),
                ("clave_cnis", models.CharField(max_length=50)),
                ("descripcion", models.TextField()),
                (
                    "precio_unitario",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "valor_total",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "insumo_en_cpm",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("inventario_disponible", models.IntegerField(default=0)),
                (
                    "unidad_medida",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                ("lote", models.CharField(blank=True, max_length=50, null=True)),
                ("fecha_caducidad", models.DateField(blank=True, null=True)),
                ("fecha_fabricacion", models.DateField(blank=True, null=True)),
                ("fecha_recepcion", models.DateField(blank=True, null=True)),
                (
                    "estado_insumo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="inventario.estadoinsumo",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Producto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "clave_cnis",
                    models.CharField(
                        max_length=50, unique=True, verbose_name="Clave/CNIS"
                    ),
                ),
                ("descripcion", models.TextField(verbose_name="Descripción")),
                ("unidad_medida", models.CharField(default="PIEZA", max_length=20)),
                (
                    "es_insumo_cpm",
                    models.BooleanField(default=False, verbose_name="Insumo en CPM"),
                ),
                (
                    "precio_unitario_referencia",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.01"))
                        ],
                        verbose_name="Precio Unitario de Referencia",
                    ),
                ),
                ("activo", models.BooleanField(default=True)),
                ("fecha_creacion", models.DateTimeField(auto_now_add=True)),
                ("fecha_actualizacion", models.DateTimeField(auto_now=True)),
                (
                    "categoria",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="inventario.categoriaproducto",
                    ),
                ),
            ],
            options={
                "verbose_name": "Producto",
                "verbose_name_plural": "Productos",
                "ordering": ["clave_cnis"],
            },
        ),
        migrations.CreateModel(
            name="OrdenSuministro",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("numero_orden", models.CharField(max_length=50, unique=True)),
                ("partida_presupuestal", models.CharField(max_length=20)),
                ("fecha_orden", models.DateField()),
                ("fecha_entrega_programada", models.DateField(blank=True, null=True)),
                ("observaciones", models.TextField(blank=True, null=True)),
                ("activo", models.BooleanField(default=True)),
                ("fecha_creacion", models.DateTimeField(auto_now_add=True)),
                ("fecha_actualizacion", models.DateTimeField(auto_now=True)),
                (
                    "fuente_financiamiento",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="inventario.fuentefinanciamiento",
                    ),
                ),
                (
                    "proveedor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="inventario.proveedor",
                    ),
                ),
            ],
            options={
                "verbose_name": "Orden de Suministro",
                "verbose_name_plural": "Órdenes de Suministro",
                "ordering": ["-fecha_orden"],
            },
        ),
        migrations.CreateModel(
            name="MovimientoInventario",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tipo_movimiento",
                    models.CharField(
                        choices=[
                            ("ENTRADA", "Entrada"),
                            ("SALIDA", "Salida"),
                            ("AJUSTE_POSITIVO", "Ajuste Positivo"),
                            ("AJUSTE_NEGATIVO", "Ajuste Negativo"),
                            ("TRANSFERENCIA_ENTRADA", "Transferencia Entrada"),
                            ("TRANSFERENCIA_SALIDA", "Transferencia Salida"),
                            ("CADUCIDAD", "Caducidad"),
                            ("DETERIORO", "Deterioro"),
                        ],
                        max_length=30,
                    ),
                ),
                ("cantidad", models.PositiveIntegerField()),
                ("cantidad_anterior", models.PositiveIntegerField()),
                ("cantidad_nueva", models.PositiveIntegerField()),
                ("motivo", models.TextField()),
                (
                    "documento_referencia",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("fecha_movimiento", models.DateTimeField(auto_now_add=True)),
                (
                    "institucion_destino",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="movimientos_destino",
                        to="inventario.institucion",
                    ),
                ),
                (
                    "lote",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="movimientos",
                        to="inventario.lote",
                    ),
                ),
                (
                    "usuario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Movimiento de Inventario",
                "verbose_name_plural": "Movimientos de Inventario",
                "ordering": ["-fecha_movimiento"],
            },
        ),
        migrations.AddField(
            model_name="lote",
            name="orden_suministro",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="inventario.ordensuministro",
            ),
        ),
        migrations.AddField(
            model_name="lote",
            name="producto",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="inventario.producto"
            ),
        ),
        migrations.AddField(
            model_name="lote",
            name="usuario_cambio_estado",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="cambios_estado_lote",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="institucion",
            name="tipo_institucion",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="inventario.tipoinstitucion",
                verbose_name="Tipo de institución",
            ),
        ),
        migrations.CreateModel(
            name="CargaInventario",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("archivo", models.FileField(upload_to="cargas_inventario/")),
                ("nombre_archivo", models.CharField(max_length=255)),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("PENDIENTE", "Pendiente"),
                            ("PROCESANDO", "Procesando"),
                            ("COMPLETADA", "Completada"),
                            ("ERROR", "Error"),
                        ],
                        default="PENDIENTE",
                        max_length=20,
                    ),
                ),
                ("total_registros", models.PositiveIntegerField(default=0)),
                ("registros_procesados", models.PositiveIntegerField(default=0)),
                ("registros_exitosos", models.PositiveIntegerField(default=0)),
                ("registros_con_error", models.PositiveIntegerField(default=0)),
                ("log_errores", models.JSONField(blank=True, null=True)),
                ("fecha_carga", models.DateTimeField(auto_now_add=True)),
                ("fecha_procesamiento", models.DateTimeField(blank=True, null=True)),
                (
                    "usuario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Carga de Inventario",
                "verbose_name_plural": "Cargas de Inventario",
                "ordering": ["-fecha_carga"],
            },
        ),
        migrations.AlterUniqueTogether(
            name="lote",
            unique_together={("numero_lote", "producto", "institucion")},
        ),
        migrations.CreateModel(
            name="AlertaCaducidad",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tipo_alerta",
                    models.CharField(
                        choices=[
                            ("30_DIAS", "30 días"),
                            ("60_DIAS", "60 días"),
                            ("90_DIAS", "90 días"),
                            ("CADUCADO", "Caducado"),
                        ],
                        max_length=20,
                    ),
                ),
                ("fecha_alerta", models.DateTimeField(auto_now_add=True)),
                ("vista", models.BooleanField(default=False)),
                ("fecha_vista", models.DateTimeField(blank=True, null=True)),
                (
                    "lote",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="inventario.lote",
                    ),
                ),
                (
                    "usuario_vista",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Alerta de Caducidad",
                "verbose_name_plural": "Alertas de Caducidad",
                "ordering": ["-fecha_alerta"],
                "unique_together": {("lote", "tipo_alerta")},
            },
        ),
    ]
