# Generated by Django 4.2.16 on 2025-10-06 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventario", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="lote",
            name="fecha_caducidad",
            field=models.DateField(blank=True, null=True),
        ),
    ]
