# Generated by Django 5.2.7 on 2025-10-07 14:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventario", "0002_alter_lote_fecha_caducidad"),
    ]

    operations = [
        migrations.AddField(
            model_name="movimientoinventario",
            name="anulado",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="movimientoinventario",
            name="fecha_anulacion",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="movimientoinventario",
            name="usuario_anulacion",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="movimientos_anulados",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
