# Generated by Django 4.2.16 on 2025-10-18 18:43

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("inventario", "0003_movimientoinventario_anulado_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="categoriaproducto",
            name="activo",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="categoriaproducto",
            name="fecha_actualizacion",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="categoriaproducto",
            name="fecha_creacion",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="categoriaproducto",
            name="origen_datos",
            field=models.CharField(
                blank=True,
                help_text="Fuente original de la categoría (CNIS, SAICA, etc.)",
                max_length=100,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="categoriaproducto",
            name="tipo",
            field=models.CharField(
                blank=True,
                help_text="Tipo de categoría, por ejemplo: Medicamento, Insumo, Equipo Médico",
                max_length=50,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="lote",
            name="clave_saica",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="Clave SAICA"
            ),
        ),
        migrations.AddField(
            model_name="lote",
            name="cns",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="CNS"
            ),
        ),
        migrations.AddField(
            model_name="lote",
            name="descripcion_saica",
            field=models.TextField(
                blank=True, null=True, verbose_name="Descripción SAICA"
            ),
        ),
        migrations.AddField(
            model_name="lote",
            name="fuente_datos",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="Fuente de Datos"
            ),
        ),
        migrations.AddField(
            model_name="lote",
            name="partida",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="Partida"
            ),
        ),
        migrations.AddField(
            model_name="lote",
            name="proveedor",
            field=models.CharField(
                blank=True, max_length=150, null=True, verbose_name="Proveedor"
            ),
        ),
        migrations.AddField(
            model_name="lote",
            name="unidad_saica",
            field=models.CharField(
                blank=True,
                max_length=50,
                null=True,
                verbose_name="Unidad de Medida (SAICA)",
            ),
        ),
        migrations.AddField(
            model_name="producto",
            name="cantidad_disponible",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                default=0,
                max_digits=10,
                null=True,
                verbose_name="Cantidad Disponible",
            ),
        ),
        migrations.AddField(
            model_name="producto",
            name="clave_saica",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="Clave SAICA"
            ),
        ),
        migrations.AddField(
            model_name="producto",
            name="descripcion_saica",
            field=models.TextField(
                blank=True, null=True, verbose_name="Descripción SAICA"
            ),
        ),
        migrations.AddField(
            model_name="producto",
            name="partida_presupuestal",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="producto",
            name="proveedor",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="producto",
            name="rfc_proveedor",
            field=models.CharField(blank=True, max_length=13, null=True),
        ),
        migrations.AddField(
            model_name="producto",
            name="unidad_medida_saica",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
