# Generated by Django 4.2.16 on 2025-10-19 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventario", "0005_movimientoinventario_contrato_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="producto",
            name="descripcion",
            field=models.TextField(max_length=255, verbose_name="Descripción"),
        ),
    ]
