# Generated by Django 4.2.16 on 2025-10-19 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventario", "0006_alter_producto_descripcion"),
    ]

    operations = [
        migrations.AlterField(
            model_name="producto",
            name="descripcion_saica",
            field=models.TextField(
                blank=True, max_length=255, null=True, verbose_name="Descripción SAICA"
            ),
        ),
    ]
