# Generated by Django 4.2.16 on 2025-10-19 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventario", "0007_alter_producto_descripcion_saica"),
    ]

    operations = [
        migrations.AlterField(
            model_name="categoriaproducto",
            name="descripcion",
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="estadoinsumo",
            name="descripcion",
            field=models.CharField(editable=False, max_length=150),
        ),
        migrations.AlterField(
            model_name="fuentefinanciamiento",
            name="descripcion",
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="lote",
            name="descripcion_saica",
            field=models.TextField(
                blank=True, max_length=255, null=True, verbose_name="Descripción SAICA"
            ),
        ),
        migrations.AlterField(
            model_name="solicitudinventario",
            name="descripcion",
            field=models.TextField(max_length=255),
        ),
        migrations.AlterField(
            model_name="tipoinstitucion",
            name="descripcion",
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
    ]
