# Generated by Django 4.2.16 on 2025-10-19 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventario", "0008_alter_categoriaproducto_descripcion_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="producto",
            name="unidad_medida_saica",
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
