# Generated by Django 4.2.16 on 2025-10-19 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventario", "0009_alter_producto_unidad_medida_saica"),
    ]

    operations = [
        migrations.AlterField(
            model_name="producto",
            name="unidad_medida",
            field=models.CharField(default="PIEZA", max_length=120),
        ),
        migrations.AlterField(
            model_name="solicitudinventario",
            name="unidad_medida",
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
