# Generated by Django 4.2.16 on 2025-10-19 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventario", "0010_alter_producto_unidad_medida_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="lote",
            name="contrato",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="lote",
            name="folio",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="lote",
            name="importe_total",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=15, null=True
            ),
        ),
        migrations.AddField(
            model_name="lote",
            name="iva",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=15, null=True
            ),
        ),
        migrations.AddField(
            model_name="lote",
            name="licitacion",
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name="lote",
            name="pedido",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="lote",
            name="remision",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="lote",
            name="responsable",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="lote",
            name="reviso",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="lote",
            name="rfc_proveedor",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="RFC Proveedor"
            ),
        ),
        migrations.AddField(
            model_name="lote",
            name="subtotal",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=15, null=True
            ),
        ),
        migrations.AddField(
            model_name="lote",
            name="tipo_entrega",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="lote",
            name="tipo_red",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
