# Generated by Django 4.2.16 on 2025-10-19 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "inventario",
            "0011_lote_contrato_lote_folio_lote_importe_total_lote_iva_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="lote",
            name="epa",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="lote",
            name="fecha_fabricacion_csv",
            field=models.DateField(
                blank=True, null=True, verbose_name="Fecha de Fabricación CSV"
            ),
        ),
        migrations.AlterField(
            model_name="lote",
            name="fecha_fabricacion",
            field=models.DateField(blank=True, null=True),
        ),
    ]
