# Generated by Django 5.2.7 on 2025-10-20 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventario", "0012_lote_epa_lote_fecha_fabricacion_csv_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="lote",
            name="clave_saica",
            field=models.CharField(
                blank=True, max_length=150, null=True, verbose_name="Clave SAICA"
            ),
        ),
        migrations.AlterField(
            model_name="lote",
            name="unidad_saica",
            field=models.CharField(
                blank=True,
                max_length=150,
                null=True,
                verbose_name="Unidad de Medida (SAICA)",
            ),
        ),
        migrations.AlterField(
            model_name="producto",
            name="clave_cnis",
            field=models.CharField(
                max_length=150, unique=True, verbose_name="Clave/CNIS"
            ),
        ),
        migrations.AlterField(
            model_name="producto",
            name="clave_saica",
            field=models.CharField(
                blank=True, max_length=150, null=True, verbose_name="Clave SAICA"
            ),
        ),
        migrations.AlterField(
            model_name="producto",
            name="descripcion",
            field=models.CharField(max_length=255, verbose_name="Descripción"),
        ),
        migrations.AlterField(
            model_name="producto",
            name="descripcion_saica",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Descripción SAICA"
            ),
        ),
        migrations.AlterField(
            model_name="producto",
            name="partida_presupuestal",
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
