# Generated by Django 5.2.7 on 2025-10-20 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventario", "0013_alter_lote_clave_saica_alter_lote_unidad_saica_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="lote",
            name="descripcion_saica",
            field=models.TextField(
                blank=True, null=True, verbose_name="Descripción SAICA"
            ),
        ),
    ]
