# Generated by Django 5.2.7 on 2025-10-20 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventario", "0014_alter_lote_descripcion_saica"),
    ]

    operations = [
        migrations.AlterField(
            model_name="producto",
            name="descripcion_saica",
            field=models.TextField(
                blank=True, null=True, verbose_name="Descripción SAICA"
            ),
        ),
    ]
