# Generated by Django 5.2.7 on 2025-10-20 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventario", "0015_alter_producto_descripcion_saica"),
    ]

    operations = [
        migrations.AlterField(
            model_name="producto",
            name="descripcion",
            field=models.TextField(verbose_name="Descripción"),
        ),
    ]
