# Generated by Django 5.2.7 on 2025-10-20 01:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventario", "0016_alter_producto_descripcion"),
    ]

    operations = [
        migrations.CreateModel(
            name="Almacen",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=150)),
                ("codigo", models.CharField(max_length=50, unique=True)),
                ("direccion", models.TextField(blank=True, null=True)),
                ("activo", models.BooleanField(default=True)),
                (
                    "institucion",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="inventario.institucion",
                        verbose_name="Institución (CLUE)",
                    ),
                ),
            ],
            options={
                "verbose_name": "Almacén",
                "verbose_name_plural": "Almacenes",
                "ordering": ["nombre"],
            },
        ),
        migrations.AddField(
            model_name="lote",
            name="almacen",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="inventario.almacen",
            ),
        ),
        migrations.CreateModel(
            name="UbicacionAlmacen",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "codigo",
                    models.CharField(max_length=50, verbose_name="Código de ubicación"),
                ),
                (
                    "descripcion",
                    models.CharField(
                        blank=True,
                        max_length=150,
                        null=True,
                        verbose_name="Descripción de la ubicación",
                    ),
                ),
                ("nivel", models.CharField(blank=True, max_length=50, null=True)),
                ("pasillo", models.CharField(blank=True, max_length=50, null=True)),
                ("rack", models.CharField(blank=True, max_length=50, null=True)),
                ("seccion", models.CharField(blank=True, max_length=50, null=True)),
                ("activo", models.BooleanField(default=True)),
                (
                    "almacen",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ubicaciones",
                        to="inventario.almacen",
                    ),
                ),
            ],
            options={
                "verbose_name": "Ubicación de Almacén",
                "verbose_name_plural": "Ubicaciones de Almacén",
                "ordering": ["almacen", "codigo"],
                "unique_together": {("almacen", "codigo")},
            },
        ),
        migrations.AddField(
            model_name="lote",
            name="ubicacion",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="inventario.ubicacionalmacen",
            ),
        ),
    ]
