# Generated by Django 4.2.16 on 2025-12-14 16:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0017_almacen_lote_almacen_ubicacionalmacen_lote_ubicacion'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConteoFisico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('folio', models.CharField(max_length=20, unique=True, verbose_name='Folio')),
                ('fecha_inicio', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Inicio')),
                ('fecha_fin', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Finalización')),
                ('estado', models.CharField(choices=[('iniciado', 'Iniciado'), ('en_progreso', 'En Progreso'), ('completado', 'Completado'), ('validado', 'Validado'), ('ajustado', 'Ajustado')], default='iniciado', max_length=20, verbose_name='Estado')),
                ('observaciones', models.TextField(blank=True, null=True, verbose_name='Observaciones')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('almacen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventario.almacen', verbose_name='Almacén')),
                ('usuario_creacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conteos_creados', to=settings.AUTH_USER_MODEL, verbose_name='Usuario que Crea')),
            ],
            options={
                'verbose_name': 'Conteo Físico',
                'verbose_name_plural': 'Conteos Físicos',
                'ordering': ['-fecha_inicio'],
            },
        ),
        migrations.CreateModel(
            name='TipoEntrega',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=10, unique=True, verbose_name='Código')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre')),
                ('descripcion', models.TextField(blank=True, null=True, verbose_name='Descripción')),
                ('prefijo_folio', models.CharField(blank=True, default='', max_length=5, verbose_name='Prefijo para Folio')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Tipo de Entrega',
                'verbose_name_plural': 'Tipos de Entrega',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='TipoRed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=10, unique=True, verbose_name='Código')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre')),
                ('descripcion', models.TextField(blank=True, null=True, verbose_name='Descripción')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Tipo de Red',
                'verbose_name_plural': 'Tipos de Red',
                'ordering': ['nombre'],
            },
        ),
        migrations.AddField(
            model_name='producto',
            name='iva',
            field=models.DecimalField(decimal_places=2, default=16, help_text='Porcentaje de IVA aplicable al producto (ej: 0 para medicamentos, 16 para insumos)', max_digits=5, verbose_name='IVA (%)'),
        ),
        migrations.AddField(
            model_name='ubicacionalmacen',
            name='estado',
            field=models.CharField(choices=[('disponible', 'Disponible'), ('ocupada', 'Ocupada'), ('bloqueada', 'Bloqueada'), ('cuarentena', 'Cuarentena'), ('caducados', 'Caducados'), ('devoluciones', 'Devoluciones')], default='disponible', max_length=20, verbose_name='Estado'),
        ),
        migrations.CreateModel(
            name='OrdenTraslado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('folio', models.CharField(max_length=20, unique=True, verbose_name='Folio')),
                ('vehiculo_placa', models.CharField(blank=True, max_length=20, null=True, verbose_name='Placa del Vehículo')),
                ('chofer_nombre', models.CharField(blank=True, max_length=100, null=True, verbose_name='Nombre del Chofer')),
                ('chofer_cedula', models.CharField(blank=True, max_length=20, null=True, verbose_name='Cédula del Chofer')),
                ('ruta', models.CharField(blank=True, max_length=200, null=True, verbose_name='Ruta')),
                ('fecha_salida', models.DateTimeField(blank=True, null=True, verbose_name='Fecha/Hora de Salida')),
                ('fecha_llegada_estimada', models.DateTimeField(blank=True, null=True, verbose_name='Fecha/Hora Llegada Estimada')),
                ('fecha_llegada_real', models.DateTimeField(blank=True, null=True, verbose_name='Fecha/Hora Llegada Real')),
                ('estado', models.CharField(choices=[('creada', 'Creada'), ('logistica_asignada', 'Logística Asignada'), ('en_transito', 'En Tránsito'), ('recibida', 'Recibida'), ('completada', 'Completada')], default='creada', max_length=30, verbose_name='Estado')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('almacen_destino', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='traslados_destino', to='inventario.almacen', verbose_name='Almacén Destino')),
                ('almacen_origen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='traslados_origen', to='inventario.almacen', verbose_name='Almacén Origen')),
                ('usuario_creacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='traslados_creados', to=settings.AUTH_USER_MODEL, verbose_name='Usuario que Crea')),
            ],
            options={
                'verbose_name': 'Orden de Traslado',
                'verbose_name_plural': 'Órdenes de Traslado',
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='ItemTraslado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField(verbose_name='Cantidad a Trasladar')),
                ('cantidad_recibida', models.PositiveIntegerField(default=0, verbose_name='Cantidad Recibida')),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('en_transito', 'En Tránsito'), ('recibido', 'Recibido')], default='pendiente', max_length=20, verbose_name='Estado')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('lote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventario.lote', verbose_name='Lote')),
                ('orden_traslado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='inventario.ordentraslado', verbose_name='Orden de Traslado')),
            ],
            options={
                'verbose_name': 'Item de Traslado',
                'verbose_name_plural': 'Items de Traslado',
            },
        ),
        migrations.CreateModel(
            name='ItemConteoFisico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_teorica', models.PositiveIntegerField(verbose_name='Cantidad Teórica')),
                ('cantidad_fisica', models.PositiveIntegerField(verbose_name='Cantidad Física')),
                ('estado_diferencia', models.CharField(choices=[('coincide', 'Coincide'), ('falta', 'Falta'), ('exceso', 'Exceso')], max_length=20, verbose_name='Estado de Diferencia')),
                ('observaciones', models.TextField(blank=True, null=True, verbose_name='Observaciones')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('conteo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='inventario.conteofisico', verbose_name='Conteo Físico')),
                ('lote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventario.lote', verbose_name='Lote')),
                ('ubicacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventario.ubicacionalmacen', verbose_name='Ubicación')),
            ],
            options={
                'verbose_name': 'Item de Conteo Físico',
                'verbose_name_plural': 'Items de Conteo Físico',
            },
        ),
        migrations.CreateModel(
            name='Folio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_consecutivo', models.IntegerField(default=0, verbose_name='Número Consecutivo')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('tipo_entrega', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='folio', to='inventario.tipoentrega')),
            ],
            options={
                'verbose_name': 'Folio',
                'verbose_name_plural': 'Folios',
            },
        ),
        migrations.CreateModel(
            name='CitaProveedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_cita', models.DateTimeField(verbose_name='Fecha y Hora de Cita')),
                ('estado', models.CharField(choices=[('programada', 'Programada'), ('autorizada', 'Autorizada'), ('completada', 'Completada'), ('cancelada', 'Cancelada')], default='programada', max_length=20, verbose_name='Estado')),
                ('observaciones', models.TextField(blank=True, null=True, verbose_name='Observaciones')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('almacen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventario.almacen', verbose_name='Almacén')),
                ('proveedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='citas', to='inventario.proveedor')),
                ('usuario_creacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='citas_creadas', to=settings.AUTH_USER_MODEL, verbose_name='Usuario que Crea')),
            ],
            options={
                'verbose_name': 'Cita de Proveedor',
                'verbose_name_plural': 'Citas de Proveedores',
                'ordering': ['-fecha_cita'],
            },
        ),
    ]
