# Generated by Django 4.2.16 on 2025-12-14 18:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0018_conteofisico_tipoentrega_tipored_producto_iva_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EstadoCita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(help_text='Identificador único del estado (ej: pendiente, autorizada)', max_length=50, unique=True, verbose_name='Código del Estado')),
                ('nombre', models.CharField(help_text='Nombre descriptivo del estado', max_length=100, verbose_name='Nombre del Estado')),
                ('descripcion', models.TextField(blank=True, help_text='Descripción detallada del estado', null=True, verbose_name='Descripción')),
                ('color', models.CharField(choices=[('primary', 'Azul'), ('secondary', 'Gris'), ('success', 'Verde'), ('danger', 'Rojo'), ('warning', 'Amarillo'), ('info', 'Celeste'), ('light', 'Claro'), ('dark', 'Oscuro')], default='secondary', help_text='Color del badge en la interfaz', max_length=20, verbose_name='Color Badge')),
                ('activo', models.BooleanField(default=True, help_text='Si está desactivado, no aparecerá en los formularios', verbose_name='Activo')),
                ('orden', models.PositiveIntegerField(default=0, help_text='Orden de aparición en listas', verbose_name='Orden')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Estado de Cita',
                'verbose_name_plural': 'Estados de Cita',
                'ordering': ['orden', 'nombre'],
            },
        ),
        migrations.AddField(
            model_name='citaproveedor',
            name='fecha_autorizacion',
            field=models.DateTimeField(blank=True, help_text='Fecha y hora cuando se autorizó la cita', null=True, verbose_name='Fecha de Autorización'),
        ),
        migrations.AddField(
            model_name='citaproveedor',
            name='usuario_autorizacion',
            field=models.ForeignKey(blank=True, help_text='Usuario que autorizó la cita', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='citas_autorizadas', to=settings.AUTH_USER_MODEL, verbose_name='Usuario que Autoriza'),
        ),
    ]
