# Generated by Django 4.2.16 on 2025-12-14 19:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0019_estadocita_citaproveedor_fecha_autorizacion_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracionNotificaciones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_habilitado', models.BooleanField(default=True, help_text='Activar/desactivar notificaciones por email', verbose_name='Email Habilitado')),
                ('email_remitente', models.EmailField(blank=True, help_text='Dirección de correo desde la cual se enviarán notificaciones', max_length=254, null=True, verbose_name='Email Remitente')),
                ('email_destinatarios', models.TextField(blank=True, help_text='Direcciones de correo separadas por comas (ej: admin@hospital.com, jefe@hospital.com)', null=True, verbose_name='Emails Destinatarios')),
                ('telegram_habilitado', models.BooleanField(default=False, help_text='Activar/desactivar notificaciones por Telegram', verbose_name='Telegram Habilitado')),
                ('telegram_token', models.CharField(blank=True, help_text='Token del bot obtenido de BotFather (@BotFather en Telegram)', max_length=255, null=True, verbose_name='Token del Bot de Telegram')),
                ('telegram_chat_id', models.CharField(blank=True, help_text='ID del chat/grupo donde se enviarán notificaciones', max_length=255, null=True, verbose_name='Chat ID de Telegram')),
                ('notificar_cita_creada', models.BooleanField(default=True, verbose_name='Notificar Cita Creada')),
                ('notificar_cita_autorizada', models.BooleanField(default=True, verbose_name='Notificar Cita Autorizada')),
                ('notificar_cita_cancelada', models.BooleanField(default=True, verbose_name='Notificar Cita Cancelada')),
                ('notificar_traslado_creado', models.BooleanField(default=True, verbose_name='Notificar Traslado Creado')),
                ('notificar_traslado_completado', models.BooleanField(default=True, verbose_name='Notificar Traslado Completado')),
                ('notificar_conteo_iniciado', models.BooleanField(default=True, verbose_name='Notificar Conteo Iniciado')),
                ('notificar_conteo_completado', models.BooleanField(default=True, verbose_name='Notificar Conteo Completado')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha Creación')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, verbose_name='Fecha Actualización')),
                ('usuario_creacion', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='config_notificaciones_creadas', to=settings.AUTH_USER_MODEL, verbose_name='Usuario Creación')),
            ],
            options={
                'verbose_name': 'Configuración de Notificaciones',
                'verbose_name_plural': 'Configuración de Notificaciones',
                'ordering': ['-fecha_actualizacion'],
            },
        ),
        migrations.CreateModel(
            name='LogNotificaciones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('email', 'Email'), ('telegram', 'Telegram'), ('ambos', 'Email y Telegram')], max_length=20, verbose_name='Tipo de Notificación')),
                ('evento', models.CharField(help_text='Evento que generó la notificación (ej: cita_creada, traslado_completado)', max_length=100, verbose_name='Evento')),
                ('asunto', models.CharField(max_length=255, verbose_name='Asunto')),
                ('mensaje', models.TextField(verbose_name='Mensaje')),
                ('destinatarios', models.TextField(help_text='Destinatarios a los que se intentó enviar', verbose_name='Destinatarios')),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('enviada', 'Enviada'), ('error', 'Error'), ('fallida', 'Fallida')], default='pendiente', max_length=20, verbose_name='Estado')),
                ('respuesta', models.TextField(blank=True, help_text='Respuesta o error del servidor de notificaciones', null=True, verbose_name='Respuesta del Servidor')),
                ('fecha_envio', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Envío')),
                ('fecha_entrega', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Entrega')),
                ('usuario_relacionado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notificaciones_recibidas', to=settings.AUTH_USER_MODEL, verbose_name='Usuario Relacionado')),
            ],
            options={
                'verbose_name': 'Log de Notificaciones',
                'verbose_name_plural': 'Logs de Notificaciones',
                'ordering': ['-fecha_envio'],
                'indexes': [models.Index(fields=['evento', '-fecha_envio'], name='inventario__evento_5103de_idx'), models.Index(fields=['estado', '-fecha_envio'], name='inventario__estado_694878_idx')],
            },
        ),
    ]
