# Generated by Django 4.2.16 on 2025-12-18 16:51

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0022_cleanup_and_create_pedidos'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentoLlegada',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tipo_documento', models.CharField(choices=[('REMISION', 'Remisión'), ('FACTURA', 'Factura'), ('CERTIFICADO_CALIDAD', 'Certificado de Calidad'), ('OTRO', 'Otro')], max_length=50)),
                ('archivo', models.FileField(upload_to='llegada_proveedores/%Y/%m/%d/')),
                ('descripcion', models.CharField(blank=True, max_length=255)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['tipo_documento', 'fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='ItemLlegada',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('clave', models.CharField(max_length=50)),
                ('descripcion', models.TextField()),
                ('unidad_medida', models.CharField(max_length=50)),
                ('tipo_red', models.CharField(choices=[('TEMPERATURA_AMBIENTE', 'Temperatura Ambiente'), ('RED_FRIA', 'Red Fría')], max_length=50)),
                ('tipo_insumo', models.CharField(choices=[('MEDICAMENTO', 'Medicamento'), ('MATERIAL_CURACION', 'Material de Curación')], max_length=50)),
                ('grupo_terapeutico', models.CharField(max_length=100)),
                ('numero_lote', models.CharField(max_length=100)),
                ('fecha_caducidad', models.DateField()),
                ('marca', models.CharField(blank=True, max_length=100)),
                ('fabricante', models.CharField(blank=True, max_length=100)),
                ('fecha_elaboracion', models.DateField(blank=True, null=True)),
                ('cantidad_emitida', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('cantidad_recibida', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('precio_unitario_sin_iva', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('porcentaje_iva', models.DecimalField(decimal_places=2, default=0, max_digits=5, validators=[django.core.validators.MinValueValidator(0)])),
                ('precio_unitario_con_iva', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('subtotal', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('importe_iva', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('importe_total', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='ItemPropuesta',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('cantidad_solicitada', models.PositiveIntegerField(verbose_name='Cantidad Solicitada')),
                ('cantidad_disponible', models.PositiveIntegerField(default=0, verbose_name='Cantidad Disponible')),
                ('cantidad_propuesta', models.PositiveIntegerField(default=0, verbose_name='Cantidad Propuesta')),
                ('cantidad_surtida', models.PositiveIntegerField(default=0, verbose_name='Cantidad Surtida')),
                ('estado', models.CharField(choices=[('DISPONIBLE', 'Disponible'), ('PARCIAL', 'Disponible Parcialmente'), ('NO_DISPONIBLE', 'No Disponible'), ('SURTIDO', 'Surtido')], default='NO_DISPONIBLE', max_length=20, verbose_name='Estado de Disponibilidad')),
                ('observaciones', models.TextField(blank=True, verbose_name='Observaciones')),
            ],
            options={
                'verbose_name': 'Item de Propuesta',
                'verbose_name_plural': 'Items de Propuesta',
                'ordering': ['producto__clave_cnis'],
            },
        ),
        migrations.CreateModel(
            name='LlegadaProveedor',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('folio', models.CharField(db_index=True, max_length=50, unique=True)),
                ('fecha_llegada_real', models.DateTimeField(default=django.utils.timezone.now)),
                ('remision', models.CharField(max_length=100)),
                ('numero_piezas_emitidas', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('numero_piezas_recibidas', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('observaciones_recepcion', models.TextField(blank=True, null=True)),
                ('estado_calidad', models.CharField(blank=True, choices=[('APROBADO', 'Aprobado'), ('RECHAZADO', 'Rechazado')], max_length=20, null=True)),
                ('observaciones_calidad', models.TextField(blank=True, null=True)),
                ('fecha_validacion_calidad', models.DateTimeField(blank=True, null=True)),
                ('firma_calidad', models.CharField(blank=True, max_length=255)),
                ('numero_factura', models.CharField(blank=True, max_length=100)),
                ('numero_orden_suministro', models.CharField(blank=True, max_length=100)),
                ('numero_contrato', models.CharField(blank=True, max_length=100)),
                ('numero_procedimiento', models.CharField(blank=True, max_length=100)),
                ('programa_presupuestario', models.CharField(blank=True, max_length=100)),
                ('tipo_compra', models.CharField(blank=True, max_length=100)),
                ('fecha_facturacion', models.DateTimeField(blank=True, null=True)),
                ('estado_supervision', models.CharField(blank=True, choices=[('VALIDADO', 'Validado'), ('RECHAZADO', 'Rechazado')], max_length=20, null=True)),
                ('observaciones_supervision', models.TextField(blank=True, null=True)),
                ('fecha_supervision', models.DateTimeField(blank=True, null=True)),
                ('firma_supervision', models.CharField(blank=True, max_length=255)),
                ('fecha_ubicacion', models.DateTimeField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('EN_RECEPCION', 'En Recepción'), ('CONTROL_CALIDAD', 'En Control de Calidad'), ('FACTURACION', 'En Facturación'), ('VALIDACION', 'En Validación'), ('UBICACION', 'Asignando Ubicación'), ('APROBADA', 'Aprobada'), ('RECHAZADA', 'Rechazada')], default='EN_RECEPCION', max_length=20)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='LoteAsignado',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('cantidad_asignada', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Cantidad Asignada')),
                ('fecha_caducidad_lote', models.DateField(verbose_name='Fecha de Caducidad del Lote')),
                ('dias_para_caducar', models.PositiveIntegerField(verbose_name='Días para Caducar')),
                ('fecha_asignacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Asignación')),
                ('fecha_surtimiento', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Surtimiento')),
                ('surtido', models.BooleanField(default=False, verbose_name='¿Fue Surtido?')),
            ],
            options={
                'verbose_name': 'Lote Asignado',
                'verbose_name_plural': 'Lotes Asignados',
                'ordering': ['fecha_caducidad_lote'],
            },
        ),
        migrations.CreateModel(
            name='PropuestaPedido',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('fecha_generacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Generación')),
                ('estado', models.CharField(choices=[('GENERADA', 'Propuesta Generada'), ('REVISADA', 'Revisada por Almacén'), ('EN_SURTIMIENTO', 'En Proceso de Surtimiento'), ('SURTIDA', 'Completamente Surtida'), ('PARCIAL', 'Parcialmente Surtida'), ('NO_DISPONIBLE', 'No Disponible'), ('CANCELADA', 'Cancelada')], default='GENERADA', max_length=20, verbose_name='Estado de la Propuesta')),
                ('fecha_revision', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Revisión')),
                ('observaciones_revision', models.TextField(blank=True, verbose_name='Observaciones de Revisión')),
                ('fecha_surtimiento', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Surtimiento')),
                ('total_solicitado', models.PositiveIntegerField(default=0, verbose_name='Total Solicitado')),
                ('total_disponible', models.PositiveIntegerField(default=0, verbose_name='Total Disponible')),
                ('total_propuesto', models.PositiveIntegerField(default=0, verbose_name='Total Propuesto')),
            ],
            options={
                'verbose_name': 'Propuesta de Pedido',
                'verbose_name_plural': 'Propuestas de Pedidos',
                'ordering': ['-fecha_generacion'],
            },
        ),
        migrations.RemoveConstraint(
            model_name='itemsolicitud',
            name='unique_solicitud_producto',
        ),
        migrations.AlterUniqueTogether(
            name='itemsolicitud',
            unique_together={('solicitud', 'producto')},
        ),
        migrations.AddField(
            model_name='propuestapedido',
            name='solicitud',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='propuesta_pedido', to='inventario.solicitudpedido', verbose_name='Solicitud de Pedido'),
        ),
        migrations.AddField(
            model_name='propuestapedido',
            name='usuario_generacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='propuestas_generadas', to=settings.AUTH_USER_MODEL, verbose_name='Usuario que Generó'),
        ),
        migrations.AddField(
            model_name='propuestapedido',
            name='usuario_revision',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='propuestas_revisadas', to=settings.AUTH_USER_MODEL, verbose_name='Usuario que Revisó'),
        ),
        migrations.AddField(
            model_name='propuestapedido',
            name='usuario_surtimiento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='propuestas_surtidas', to=settings.AUTH_USER_MODEL, verbose_name='Usuario que Surtió'),
        ),
        migrations.AddField(
            model_name='loteasignado',
            name='item_propuesta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lotes_asignados', to='inventario.itempropuesta', verbose_name='Item de Propuesta'),
        ),
        migrations.AddField(
            model_name='loteasignado',
            name='lote',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventario.lote', verbose_name='Lote'),
        ),
        migrations.AddField(
            model_name='llegadaproveedor',
            name='cita',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='llegada_proveedor', to='inventario.citaproveedor'),
        ),
        migrations.AddField(
            model_name='llegadaproveedor',
            name='creado_por',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='llegadas_creadas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='llegadaproveedor',
            name='proveedor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventario.proveedor'),
        ),
        migrations.AddField(
            model_name='llegadaproveedor',
            name='usuario_calidad',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='llegadas_validadas_calidad', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='llegadaproveedor',
            name='usuario_facturacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='llegadas_facturadas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='llegadaproveedor',
            name='usuario_supervision',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='llegadas_supervisadas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='llegadaproveedor',
            name='usuario_ubicacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='llegadas_ubicadas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='itempropuesta',
            name='item_solicitud',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items_propuesta', to='inventario.itemsolicitud', verbose_name='Item de Solicitud'),
        ),
        migrations.AddField(
            model_name='itempropuesta',
            name='producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventario.producto', verbose_name='Producto'),
        ),
        migrations.AddField(
            model_name='itempropuesta',
            name='propuesta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='inventario.propuestapedido', verbose_name='Propuesta de Pedido'),
        ),
        migrations.AddField(
            model_name='itemllegada',
            name='llegada',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='inventario.llegadaproveedor'),
        ),
        migrations.AddField(
            model_name='itemllegada',
            name='lote_creado',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='item_llegada', to='inventario.lote'),
        ),
        migrations.AddField(
            model_name='itemllegada',
            name='producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventario.producto'),
        ),
        migrations.AddField(
            model_name='documentollegada',
            name='llegada',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documentos', to='inventario.llegadaproveedor'),
        ),
        migrations.AddIndex(
            model_name='llegadaproveedor',
            index=models.Index(fields=['folio'], name='inventario__folio_88b7f2_idx'),
        ),
        migrations.AddIndex(
            model_name='llegadaproveedor',
            index=models.Index(fields=['estado'], name='inventario__estado_b470ba_idx'),
        ),
        migrations.AddIndex(
            model_name='llegadaproveedor',
            index=models.Index(fields=['cita'], name='inventario__cita_id_d23e95_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='itemllegada',
            unique_together={('llegada', 'numero_lote', 'producto')},
        ),
    ]
