# Generated by Django 4.2.16 on 2025-12-18 02:58

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0022_cleanup_and_create_pedidos'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemPropuesta',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('cantidad_solicitada', models.PositiveIntegerField(verbose_name='Cantidad Solicitada')),
                ('cantidad_disponible', models.PositiveIntegerField(default=0, verbose_name='Cantidad Disponible')),
                ('cantidad_propuesta', models.PositiveIntegerField(default=0, verbose_name='Cantidad Propuesta')),
                ('cantidad_surtida', models.PositiveIntegerField(default=0, verbose_name='Cantidad Surtida')),
                ('estado', models.CharField(choices=[('DISPONIBLE', 'Disponible'), ('PARCIAL', 'Disponible Parcialmente'), ('NO_DISPONIBLE', 'No Disponible'), ('SURTIDO', 'Surtido')], default='NO_DISPONIBLE', max_length=20, verbose_name='Estado de Disponibilidad')),
                ('observaciones', models.TextField(blank=True, verbose_name='Observaciones')),
            ],
            options={
                'verbose_name': 'Item de Propuesta',
                'verbose_name_plural': 'Items de Propuesta',
                'ordering': ['producto__clave_cnis'],
            },
        ),
        migrations.CreateModel(
            name='LoteAsignado',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('cantidad_asignada', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Cantidad Asignada')),
                ('fecha_caducidad_lote', models.DateField(verbose_name='Fecha de Caducidad del Lote')),
                ('dias_para_caducar', models.PositiveIntegerField(verbose_name='Días para Caducar')),
                ('fecha_asignacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Asignación')),
                ('fecha_surtimiento', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Surtimiento')),
                ('surtido', models.BooleanField(default=False, verbose_name='¿Fue Surtido?')),
            ],
            options={
                'verbose_name': 'Lote Asignado',
                'verbose_name_plural': 'Lotes Asignados',
                'ordering': ['fecha_caducidad_lote'],
            },
        ),
        migrations.CreateModel(
            name='PropuestaPedido',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('fecha_generacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Generación')),
                ('estado', models.CharField(choices=[('GENERADA', 'Propuesta Generada'), ('REVISADA', 'Revisada por Almacén'), ('EN_SURTIMIENTO', 'En Proceso de Surtimiento'), ('SURTIDA', 'Completamente Surtida'), ('PARCIAL', 'Parcialmente Surtida'), ('NO_DISPONIBLE', 'No Disponible'), ('CANCELADA', 'Cancelada')], default='GENERADA', max_length=20, verbose_name='Estado de la Propuesta')),
                ('fecha_revision', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Revisión')),
                ('observaciones_revision', models.TextField(blank=True, verbose_name='Observaciones de Revisión')),
                ('fecha_surtimiento', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Surtimiento')),
                ('total_solicitado', models.PositiveIntegerField(default=0, verbose_name='Total Solicitado')),
                ('total_disponible', models.PositiveIntegerField(default=0, verbose_name='Total Disponible')),
                ('total_propuesto', models.PositiveIntegerField(default=0, verbose_name='Total Propuesto')),
            ],
            options={
                'verbose_name': 'Propuesta de Pedido',
                'verbose_name_plural': 'Propuestas de Pedidos',
                'ordering': ['-fecha_generacion'],
            },
        ),
        migrations.RemoveConstraint(
            model_name='itemsolicitud',
            name='unique_solicitud_producto',
        ),
        migrations.AlterUniqueTogether(
            name='itemsolicitud',
            unique_together={('solicitud', 'producto')},
        ),
        migrations.AddField(
            model_name='propuestapedido',
            name='solicitud',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='propuesta_pedido', to='inventario.solicitudpedido', verbose_name='Solicitud de Pedido'),
        ),
        migrations.AddField(
            model_name='propuestapedido',
            name='usuario_generacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='propuestas_generadas', to=settings.AUTH_USER_MODEL, verbose_name='Usuario que Generó'),
        ),
        migrations.AddField(
            model_name='propuestapedido',
            name='usuario_revision',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='propuestas_revisadas', to=settings.AUTH_USER_MODEL, verbose_name='Usuario que Revisó'),
        ),
        migrations.AddField(
            model_name='propuestapedido',
            name='usuario_surtimiento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='propuestas_surtidas', to=settings.AUTH_USER_MODEL, verbose_name='Usuario que Surtió'),
        ),
        migrations.AddField(
            model_name='loteasignado',
            name='item_propuesta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lotes_asignados', to='inventario.itempropuesta', verbose_name='Item de Propuesta'),
        ),
        migrations.AddField(
            model_name='loteasignado',
            name='lote',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventario.lote', verbose_name='Lote'),
        ),
        migrations.AddField(
            model_name='itempropuesta',
            name='item_solicitud',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items_propuesta', to='inventario.itemsolicitud', verbose_name='Item de Solicitud'),
        ),
        migrations.AddField(
            model_name='itempropuesta',
            name='producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventario.producto', verbose_name='Producto'),
        ),
        migrations.AddField(
            model_name='itempropuesta',
            name='propuesta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='inventario.propuestapedido', verbose_name='Propuesta de Pedido'),
        ),
    ]
