# Generated by Django 4.2.16 on 2025-12-18 04:33

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0023_itempropuesta_loteasignado_propuestapedido_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LlegadaProveedor',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('folio', models.CharField(db_index=True, max_length=50, unique=True)),
                ('fecha_llegada_real', models.DateTimeField(default=django.utils.timezone.now)),
                ('remision', models.CharField(max_length=100)),
                ('numero_piezas_emitidas', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('numero_piezas_recibidas', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('observaciones_recepcion', models.TextField(blank=True, null=True)),
                ('estado_calidad', models.CharField(blank=True, choices=[('APROBADO', 'Aprobado'), ('RECHAZADO', 'Rechazado')], max_length=20, null=True)),
                ('observaciones_calidad', models.TextField(blank=True, null=True)),
                ('fecha_validacion_calidad', models.DateTimeField(blank=True, null=True)),
                ('firma_calidad', models.CharField(blank=True, max_length=255)),
                ('numero_factura', models.CharField(blank=True, max_length=100)),
                ('numero_orden_suministro', models.CharField(blank=True, max_length=100)),
                ('numero_contrato', models.CharField(blank=True, max_length=100)),
                ('numero_procedimiento', models.CharField(blank=True, max_length=100)),
                ('programa_presupuestario', models.CharField(blank=True, max_length=100)),
                ('tipo_compra', models.CharField(blank=True, max_length=100)),
                ('fecha_facturacion', models.DateTimeField(blank=True, null=True)),
                ('estado_supervision', models.CharField(blank=True, choices=[('VALIDADO', 'Validado'), ('RECHAZADO', 'Rechazado')], max_length=20, null=True)),
                ('observaciones_supervision', models.TextField(blank=True, null=True)),
                ('fecha_supervision', models.DateTimeField(blank=True, null=True)),
                ('firma_supervision', models.CharField(blank=True, max_length=255)),
                ('fecha_ubicacion', models.DateTimeField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('EN_RECEPCION', 'En Recepción'), ('CONTROL_CALIDAD', 'En Control de Calidad'), ('FACTURACION', 'En Facturación'), ('VALIDACION', 'En Validación'), ('UBICACION', 'Asignando Ubicación'), ('APROBADA', 'Aprobada'), ('RECHAZADA', 'Rechazada')], default='EN_RECEPCION', max_length=20)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('cita', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='llegada_proveedor', to='inventario.citaproveedor')),
                ('creado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='llegadas_creadas', to=settings.AUTH_USER_MODEL)),
                ('proveedor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventario.proveedor')),
                ('usuario_calidad', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='llegadas_validadas_calidad', to=settings.AUTH_USER_MODEL)),
                ('usuario_facturacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='llegadas_facturadas', to=settings.AUTH_USER_MODEL)),
                ('usuario_supervision', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='llegadas_supervisadas', to=settings.AUTH_USER_MODEL)),
                ('usuario_ubicacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='llegadas_ubicadas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='ItemLlegada',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('clave', models.CharField(max_length=50)),
                ('descripcion', models.TextField()),
                ('unidad_medida', models.CharField(max_length=50)),
                ('tipo_red', models.CharField(choices=[('TEMPERATURA_AMBIENTE', 'Temperatura Ambiente'), ('RED_FRIA', 'Red Fría')], max_length=50)),
                ('tipo_insumo', models.CharField(choices=[('MEDICAMENTO', 'Medicamento'), ('MATERIAL_CURACION', 'Material de Curación')], max_length=50)),
                ('grupo_terapeutico', models.CharField(max_length=100)),
                ('numero_lote', models.CharField(max_length=100)),
                ('fecha_caducidad', models.DateField()),
                ('marca', models.CharField(blank=True, max_length=100)),
                ('fabricante', models.CharField(blank=True, max_length=100)),
                ('fecha_elaboracion', models.DateField(blank=True, null=True)),
                ('cantidad_emitida', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('cantidad_recibida', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('precio_unitario_sin_iva', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('porcentaje_iva', models.DecimalField(decimal_places=2, default=0, max_digits=5, validators=[django.core.validators.MinValueValidator(0)])),
                ('precio_unitario_con_iva', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('subtotal', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('importe_iva', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('importe_total', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('llegada', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='inventario.llegadaproveedor')),
                ('lote_creado', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='item_llegada', to='inventario.lote')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventario.producto')),
            ],
            options={
                'ordering': ['fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='DocumentoLlegada',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tipo_documento', models.CharField(choices=[('REMISION', 'Remisión'), ('FACTURA', 'Factura'), ('CERTIFICADO_CALIDAD', 'Certificado de Calidad'), ('OTRO', 'Otro')], max_length=50)),
                ('archivo', models.FileField(upload_to='llegada_proveedores/%Y/%m/%d/')),
                ('descripcion', models.CharField(blank=True, max_length=255)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('llegada', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documentos', to='inventario.llegadaproveedor')),
            ],
            options={
                'ordering': ['tipo_documento', 'fecha_creacion'],
            },
        ),
        migrations.AddIndex(
            model_name='llegadaproveedor',
            index=models.Index(fields=['folio'], name='inventario__folio_88b7f2_idx'),
        ),
        migrations.AddIndex(
            model_name='llegadaproveedor',
            index=models.Index(fields=['estado'], name='inventario__estado_b470ba_idx'),
        ),
        migrations.AddIndex(
            model_name='llegadaproveedor',
            index=models.Index(fields=['cita'], name='inventario__cita_id_d23e95_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='itemllegada',
            unique_together={('llegada', 'numero_lote', 'producto')},
        ),
    ]
