# Generated by Django 4.2.16 on 2025-12-18 19:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0026_devolucion_proveedor'),
        ('inventario', '0024_llegadaproveedor_itemllegada_documentollegada_and_more'),
    ]

    operations = [
    ]
