# Generated by Django 4.2.16 on 2025-12-18 19:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0023_itempropuesta_loteasignado_propuestapedido_and_more'),
        ('inventario', '0026_devolucion_proveedor'),
    ]

    operations = [
    ]
