# Generated by Django 4.2.16 on 2025-12-22 18:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0023_documentollegada_itemllegada_itempropuesta_and_more'),
        ('inventario', '0031_hacer_menu_item_flexible'),
    ]

    operations = [
    ]
