# Generated by Django 4.2.16 on 2025-12-22 16:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('inventario', '0031_hacer_menu_item_flexible'),
    ]

    operations = [
        migrations.CreateModel(
            name='DistribucionArea',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('area_destino', models.CharField(max_length=100, verbose_name='Área de Destino')),
                ('responsable_area', models.CharField(max_length=100, verbose_name='Responsable del Área')),
                ('telefono_responsable', models.CharField(blank=True, max_length=20, verbose_name='Teléfono')),
                ('email_responsable', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('EN_TRANSITO', 'En Tránsito'), ('ENTREGADA', 'Entregada'), ('RECHAZADA', 'Rechazada')], default='PENDIENTE', max_length=20, verbose_name='Estado')),
                ('fecha_entrega_estimada', models.DateField(verbose_name='Fecha de Entrega Estimada')),
                ('fecha_entrega_real', models.DateField(blank=True, null=True, verbose_name='Fecha de Entrega Real')),
                ('recibido_por', models.CharField(blank=True, max_length=100, verbose_name='Recibido por')),
                ('firma_recibido', models.TextField(blank=True, verbose_name='Firma (Base64)')),
                ('observaciones_entrega', models.TextField(blank=True, verbose_name='Observaciones de Entrega')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Distribución a Área',
                'verbose_name_plural': 'Distribuciones a Áreas',
                'db_table': 'inventario_distribucionarea',
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='ItemDistribucion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('cantidad', models.PositiveIntegerField(verbose_name='Cantidad Distribuida')),
                ('precio_unitario', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Precio Unitario')),
                ('observaciones', models.TextField(blank=True, verbose_name='Observaciones')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Item de Distribución',
                'verbose_name_plural': 'Items de Distribución',
                'db_table': 'inventario_itemdistribucion',
            },
        ),
        migrations.CreateModel(
            name='ItemSalidaExistencias',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('cantidad', models.PositiveIntegerField(verbose_name='Cantidad')),
                ('precio_unitario', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Precio Unitario')),
                ('observaciones', models.TextField(blank=True, verbose_name='Observaciones')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Item de Salida',
                'verbose_name_plural': 'Items de Salida',
                'db_table': 'inventario_itemsalidaexistencias',
            },
        ),
        migrations.CreateModel(
            name='SalidaExistencias',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('folio', models.CharField(max_length=50, unique=True, verbose_name='Folio')),
                ('fecha_salida', models.DateTimeField(verbose_name='Fecha de Salida')),
                ('nombre_receptor', models.CharField(max_length=200, verbose_name='Nombre del Receptor')),
                ('firma_receptor', models.TextField(verbose_name='Firma del Receptor')),
                ('observaciones', models.TextField(verbose_name='Observaciones')),
            ],
            options={
                'verbose_name': 'Salida de Existencias',
                'verbose_name_plural': 'Salidas de Existencias',
                'db_table': 'inventario_salidaexistencias',
                'ordering': ['-fecha_salida'],
            },
        ),
        migrations.AlterModelOptions(
            name='devolucionproveedor',
            options={'ordering': ['-fecha_creacion'], 'verbose_name': 'Devolución a Proveedor', 'verbose_name_plural': 'Devoluciones a Proveedores'},
        ),
        migrations.AlterModelOptions(
            name='itemdevolucion',
            options={'verbose_name': 'Item de Devolución', 'verbose_name_plural': 'Items de Devolución'},
        ),
        migrations.RemoveField(
            model_name='devolucionproveedor',
            name='motivo_cancelacion',
        ),
        migrations.AlterField(
            model_name='devolucionproveedor',
            name='contacto_proveedor',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='devolucionproveedor',
            name='email_proveedor',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='devolucionproveedor',
            name='estado',
            field=models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('AUTORIZADA', 'Autorizada'), ('COMPLETADA', 'Completada'), ('CANCELADA', 'Cancelada')], default='PENDIENTE', max_length=20),
        ),
        migrations.AlterField(
            model_name='devolucionproveedor',
            name='institucion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventario.institucion'),
        ),
        migrations.AlterField(
            model_name='devolucionproveedor',
            name='lotes',
            field=models.ManyToManyField(related_name='devoluciones', through='inventario.ItemDevolucion', to='inventario.lote'),
        ),
        migrations.AlterField(
            model_name='devolucionproveedor',
            name='monto_nota_credito',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='devolucionproveedor',
            name='motivo_general',
            field=models.CharField(choices=[('DEFECTUOSO', 'Producto Defectuoso'), ('CADUCADO', 'Producto Caducado'), ('INCORRECTO', 'Producto Incorrecto'), ('CANTIDAD_INCORRECTA', 'Cantidad Incorrecta'), ('EMBALAJE_DAÑADO', 'Embalaje Dañado'), ('NO_CONFORME', 'No Conforme con Especificaciones'), ('SOLICITUD_CLIENTE', 'Solicitud del Cliente'), ('OTROS', 'Otros')], max_length=20),
        ),
        migrations.AlterField(
            model_name='devolucionproveedor',
            name='numero_autorizacion',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='devolucionproveedor',
            name='numero_nota_credito',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='devolucionproveedor',
            name='proveedor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventario.proveedor'),
        ),
        migrations.AlterField(
            model_name='devolucionproveedor',
            name='telefono_proveedor',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='devolucionproveedor',
            name='usuario_creacion',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='devoluciones_creadas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='itemdevolucion',
            name='devolucion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventario.devolucionproveedor'),
        ),
        migrations.AlterField(
            model_name='itemdevolucion',
            name='lote',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventario.lote'),
        ),
        migrations.AlterField(
            model_name='itemdevolucion',
            name='motivo_especifico',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='itemdevolucion',
            name='observaciones_inspeccion',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='itemdevolucion',
            name='precio_unitario',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='itemdevolucion',
            name='usuario_inspeccion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='items_devolucion_inspeccionados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='menuitemrol',
            name='es_submenu',
            field=models.BooleanField(default=False, help_text='Marcar si es un elemento de submenú', verbose_name='Es Submenú'),
        ),
        migrations.AlterField(
            model_name='menuitemrol',
            name='icono',
            field=models.CharField(default='fas fa-circle', help_text='Clase Font Awesome para el icono (ej: fas fa-home)', max_length=50, verbose_name='Icono Font Awesome'),
        ),
        migrations.AlterField(
            model_name='menuitemrol',
            name='menu_padre',
            field=models.ForeignKey(blank=True, help_text='Si es un submenú, selecciona el menú padre', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submenus', to='inventario.menuitemrol', verbose_name='Menú Padre'),
        ),
        migrations.AlterField(
            model_name='menuitemrol',
            name='nombre_mostrado',
            field=models.CharField(help_text='Nombre que se muestra en el menú', max_length=100, verbose_name='Nombre Mostrado'),
        ),
        migrations.AlterField(
            model_name='menuitemrol',
            name='orden',
            field=models.IntegerField(default=0, help_text='Orden de aparición en el menú', verbose_name='Orden'),
        ),
        migrations.AlterField(
            model_name='menuitemrol',
            name='roles_permitidos',
            field=models.ManyToManyField(help_text='Selecciona los roles que pueden ver esta opción', to='auth.group', verbose_name='Roles Permitidos'),
        ),
        migrations.AlterField(
            model_name='menuitemrol',
            name='url_name',
            field=models.CharField(help_text='Nombre de la URL en urls.py (ej: dashboard, lista_productos)', max_length=100, verbose_name='Nombre de URL'),
        ),
        migrations.AlterUniqueTogether(
            name='itemdevolucion',
            unique_together={('devolucion', 'lote')},
        ),
        migrations.AddIndex(
            model_name='devolucionproveedor',
            index=models.Index(fields=['folio'], name='inventario__folio_c51649_idx'),
        ),
        migrations.AddIndex(
            model_name='devolucionproveedor',
            index=models.Index(fields=['estado', '-fecha_creacion'], name='inventario__estado_f26bfa_idx'),
        ),
        migrations.AddIndex(
            model_name='devolucionproveedor',
            index=models.Index(fields=['proveedor', '-fecha_creacion'], name='inventario__proveed_ba3f9e_idx'),
        ),
        migrations.AddIndex(
            model_name='devolucionproveedor',
            index=models.Index(fields=['institucion', '-fecha_creacion'], name='inventario__institu_d57594_idx'),
        ),
        migrations.AlterModelTable(
            name='devolucionproveedor',
            table='inventario_devolucionproveedor',
        ),
        migrations.AlterModelTable(
            name='itemdevolucion',
            table='inventario_itemdevolucion',
        ),
        migrations.AddField(
            model_name='salidaexistencias',
            name='almacen_origen',
            field=models.ForeignKey(db_column='almacen_origen_id', on_delete=django.db.models.deletion.PROTECT, to='inventario.almacen', verbose_name='Almacén Origen'),
        ),
        migrations.AddField(
            model_name='salidaexistencias',
            name='institucion_destino',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventario.institucion', verbose_name='Institución Destino'),
        ),
        migrations.AddField(
            model_name='salidaexistencias',
            name='solicitud',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='inventario.solicitudinventario', verbose_name='Solicitud'),
        ),
        migrations.AddField(
            model_name='salidaexistencias',
            name='usuario_autoriza',
            field=models.ForeignKey(blank=True, db_column='usuario_autoriza_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='salidas_autorizadas', to=settings.AUTH_USER_MODEL, verbose_name='Usuario que Autoriza'),
        ),
        migrations.AddField(
            model_name='itemsalidaexistencias',
            name='lote',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventario.lote', verbose_name='Lote'),
        ),
        migrations.AddField(
            model_name='itemsalidaexistencias',
            name='salida',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itemsalidaexistencias_set', to='inventario.salidaexistencias'),
        ),
        migrations.AddField(
            model_name='itemdistribucion',
            name='distribucion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itemdistribucion_set', to='inventario.distribucionarea'),
        ),
        migrations.AddField(
            model_name='itemdistribucion',
            name='item_salida',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventario.itemsalidaexistencias', verbose_name='Item de Salida'),
        ),
        migrations.AddField(
            model_name='distribucionarea',
            name='salida',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='distribuciones', to='inventario.salidaexistencias'),
        ),
        migrations.AddField(
            model_name='distribucionarea',
            name='usuario_creacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='distribuciones_creadas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='itemsalidaexistencias',
            unique_together={('salida', 'lote')},
        ),
    ]
