# Generated by Django 4.2.16 on 2025-12-26 00:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0032_add_lote_ubicacion_model'),
        ('inventario', '0032_distribucionarea_itemdistribucion_and_more'),
    ]

    operations = [
    ]
