# Generated by Django 4.2.16 on 2025-12-26 01:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0032_merge_20251222_1239'),
        ('inventario', '0033_merge_20251225_1846'),
    ]

    operations = [
    ]
