# Generated by Django 4.2.16 on 2025-12-26 00:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0033_distribucionarea_itemdistribucion_and_more'),
        ('inventario', '0033_merge_20251225_1846'),
    ]

    operations = [
    ]
