# Generated by Django 4.2.16 on 2025-12-26 18:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0035_add_ubicacion_to_loteasignado'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='loteasignado',
            options={'ordering': ['lote_ubicacion__lote__fecha_caducidad'], 'verbose_name': 'Lote Asignado', 'verbose_name_plural': 'Lotes Asignados'},
        ),
        migrations.RemoveField(
            model_name='loteasignado',
            name='cantidad_en_ubicacion',
        ),
        migrations.RemoveField(
            model_name='loteasignado',
            name='dias_para_caducar',
        ),
        migrations.RemoveField(
            model_name='loteasignado',
            name='fecha_caducidad_lote',
        ),
        migrations.RemoveField(
            model_name='loteasignado',
            name='lote',
        ),
        migrations.RemoveField(
            model_name='loteasignado',
            name='ubicacion',
        ),
        migrations.AddField(
            model_name='loteasignado',
            name='lote_ubicacion',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='asignaciones_propuesta', to='inventario.loteubicacion', verbose_name='Ubicación del Lote Asignado'),
            preserve_default=False,
        ),
    ]
