# Generated by Django 4.2.16 on 2025-12-27 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0036_alter_loteasignado_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lote',
            name='cantidad_reservada',
            field=models.PositiveIntegerField(default=0, verbose_name='Cantidad Reservada en Propuestas'),
        ),
    ]
