# Generated by Django 4.2.16 on 2026-01-04 02:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0002_agregar_dashboard_movimientos_menu'),
        ('inventario', '0037_add_cantidad_reservada_to_lote'),
    ]

    operations = [
    ]
