# Generated by Django 4.2.16 on 2026-01-04 03:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0038_merge_20260103_2058'),
        ('inventario', '0039_logsistema'),
    ]

    operations = [
    ]
