# Generated by Django 4.2.16 on 2026-01-04 04:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0038_merge_20260103_2058'),
    ]

    operations = [
        migrations.CreateModel(
            name='LogSistema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nivel', models.CharField(choices=[('DEBUG', 'Debug'), ('INFO', 'Información'), ('WARNING', 'Advertencia'), ('ERROR', 'Error'), ('CRITICAL', 'Crítico')], db_index=True, default='INFO', max_length=10)),
                ('tipo', models.CharField(choices=[('ESTATICO', 'Archivo Estático'), ('BASE_DATOS', 'Base de Datos'), ('AUTENTICACION', 'Autenticación'), ('NEGOCIO', 'Lógica de Negocio'), ('SISTEMA', 'Sistema'), ('SEGURIDAD', 'Seguridad'), ('OTRO', 'Otro')], db_index=True, default='OTRO', max_length=20)),
                ('titulo', models.CharField(db_index=True, max_length=255)),
                ('mensaje', models.TextField()),
                ('detalles', models.JSONField(blank=True, default=dict)),
                ('url', models.CharField(blank=True, max_length=500, null=True)),
                ('ip_cliente', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('resuelto', models.BooleanField(db_index=True, default=False)),
                ('fecha_resolucion', models.DateTimeField(blank=True, null=True)),
                ('notas_resolucion', models.TextField(blank=True)),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='logs_sistema', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Log del Sistema',
                'verbose_name_plural': 'Logs del Sistema',
                'ordering': ['-fecha_creacion'],
                'indexes': [models.Index(fields=['-fecha_creacion', 'nivel'], name='inventario__fecha_c_ae1258_idx'), models.Index(fields=['-fecha_creacion', 'tipo'], name='inventario__fecha_c_4e7acb_idx'), models.Index(fields=['resuelto', '-fecha_creacion'], name='inventario__resuelt_d26045_idx')],
            },
        ),
    ]
