# Generated by Django 4.2.16 on 2026-01-08 00:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0041_merge_20260104_0027'),
        ('inventario', '0042_add_registro_conteo_fisico'),
    ]

    operations = [
    ]
