# Generated by Django 4.2.16 on 2026-01-10 23:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0043_cargainventario_productos_no_procesados'),
        ('inventario', '0043_merge_20260107_1854'),
    ]

    operations = [
    ]
