# Generated by Django 4.2.16 on 2026-01-17 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0045_logpropuesta'),
    ]

    operations = [
        migrations.AddField(
            model_name='citaproveedor',
            name='clave_medicamento',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Clave de Medicamento (CNIS)'),
        ),
        migrations.AddField(
            model_name='citaproveedor',
            name='fecha_expedicion',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de Expedición'),
        ),
        migrations.AddField(
            model_name='citaproveedor',
            name='fecha_limite_entrega',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha Límite de Entrega'),
        ),
        migrations.AddField(
            model_name='citaproveedor',
            name='numero_contrato',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Número de Contrato'),
        ),
        migrations.AddField(
            model_name='citaproveedor',
            name='numero_orden_remision',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Número de Orden de Remisión'),
        ),
        migrations.AddField(
            model_name='citaproveedor',
            name='numero_orden_suministro',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Número de Orden de Suministro'),
        ),
        migrations.AddField(
            model_name='citaproveedor',
            name='tipo_transporte',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Tipo de Transporte'),
        ),
        migrations.AlterField(
            model_name='solicitudpedido',
            name='observaciones_solicitud',
            field=models.TextField(blank=True, verbose_name='Folio del Pedido'),
        ),
    ]
