# Generated by Django 4.2.16 on 2026-01-17 18:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0046_citaproveedor_clave_medicamento_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ListaRevision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('folio', models.CharField(db_index=True, max_length=100, unique=True)),
                ('tipo_documento', models.CharField(choices=[('factura', 'Factura'), ('remision', 'Remisión')], default='factura', max_length=20)),
                ('numero_documento', models.CharField(blank=True, max_length=100)),
                ('fecha_documento', models.DateField(blank=True, null=True)),
                ('proveedor', models.CharField(max_length=255)),
                ('numero_control', models.CharField(blank=True, max_length=100)),
                ('numero_prealta', models.CharField(blank=True, max_length=100)),
                ('numero_alta', models.CharField(blank=True, max_length=100)),
                ('numero_contrato', models.CharField(blank=True, max_length=100)),
                ('pedido', models.CharField(blank=True, max_length=100)),
                ('origen', models.CharField(choices=[('imss', 'IMSS Bienestar'), ('transferencia', 'Transferencia'), ('otro', 'Otro')], default='imss', max_length=20)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('aprobada', 'Aprobada'), ('rechazada', 'Rechazada')], default='pendiente', max_length=20)),
                ('justificacion_rechazo', models.TextField(blank=True, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_validacion', models.DateTimeField(blank=True, null=True)),
                ('observaciones', models.TextField(blank=True)),
                ('cita', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='lista_revision', to='inventario.citaproveedor')),
                ('usuario_creacion', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='listas_revision_creadas', to=settings.AUTH_USER_MODEL)),
                ('usuario_validacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='listas_revision_validadas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Lista de Revisión',
                'verbose_name_plural': 'Listas de Revisión',
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='ItemRevision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=500)),
                ('resultado', models.CharField(choices=[('si', 'SI'), ('no', 'NO'), ('na', 'N/A')], default='si', max_length=10)),
                ('observaciones', models.TextField(blank=True)),
                ('orden', models.PositiveIntegerField(default=0)),
                ('lista_revision', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='inventario.listarevision')),
            ],
            options={
                'verbose_name': 'Item de Revisión',
                'verbose_name_plural': 'Items de Revisión',
                'ordering': ['orden'],
            },
        ),
    ]
