# Generated by Django 4.2.16 on 2026-01-17 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0047_listarevision_itemrevision'),
    ]

    operations = [
        migrations.AddField(
            model_name='citaproveedor',
            name='folio',
            field=models.CharField(blank=True, db_index=True, max_length=20, null=True, unique=True, verbose_name='Folio'),
        ),
    ]
