# Generated by Django 4.2.16 on 2026-01-17 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0048_citaproveedor_folio'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemrevision',
            name='tipo_control',
            field=models.CharField(choices=[('radio', 'Radio Button (SI/NO/N/A)'), ('checkbox', 'Checkbox (Aplica/No Aplica)')], default='radio', max_length=20),
        ),
    ]
