# Generated by Django 4.2.16 on 2026-01-17 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0049_itemrevision_tipo_control'),
    ]

    operations = [
        migrations.AddField(
            model_name='citaproveedor',
            name='tipo_entrega',
            field=models.CharField(choices=[('entrega_directa', 'Entrega Directa'), ('operador_logistico', 'Operador Logístico'), ('sedesa', 'Sedesa'), ('transferencia', 'Transferencia'), ('canje', 'Canje'), ('donacion', 'Donación')], default='entrega_directa', max_length=20, verbose_name='Tipo de Entrega'),
        ),
    ]
