# Generated by Django 4.2.16 on 2026-01-18 01:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0025_merge_0024_migrations'),
        ('inventario', '0050_citaproveedor_tipo_entrega'),
    ]

    operations = [
    ]
