# Generated by Django 4.2.16 on 2025-01-22

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0102_add_cantidad_reservada_to_lote_ubicacion'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductoNoDisponibleAlmacen',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('cantidad_requerida', models.PositiveIntegerField(verbose_name='Cantidad Requerida')),
                ('cantidad_disponible_destino', models.PositiveIntegerField(default=0, verbose_name='Cantidad Disponible en Almacén Destino')),
                ('cantidad_disponible_otros', models.PositiveIntegerField(default=0, verbose_name='Cantidad Disponible en Otros Almacenes')),
                ('almacenes_con_disponibilidad', models.TextField(blank=True, help_text='Lista de almacenes que tienen el producto disponible (JSON o texto)', verbose_name='Almacenes con Disponibilidad')),
                ('notificado_telegram', models.BooleanField(default=False, verbose_name='Notificado por Telegram')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Registro')),
                ('almacen_destino', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productos_no_disponibles', to='inventario.almacen', verbose_name='Almacén Destino')),
                ('item_propuesta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registros_no_disponible', to='inventario.itempropuesta', verbose_name='Item de Propuesta')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registros_no_disponible_almacen', to='inventario.producto', verbose_name='Producto')),
                ('propuesta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productos_no_disponibles', to='inventario.propuestapedido', verbose_name='Propuesta')),
            ],
            options={
                'verbose_name': 'Producto No Disponible en Almacén',
                'verbose_name_plural': 'Productos No Disponibles en Almacén',
                'ordering': ['-fecha_registro'],
            },
        ),
        migrations.AddIndex(
            model_name='productonodisponiblealmacen',
            index=models.Index(fields=['propuesta', 'producto'], name='inventario_propuest_0_idx'),
        ),
        migrations.AddIndex(
            model_name='productonodisponiblealmacen',
            index=models.Index(fields=['almacen_destino', 'notificado_telegram'], name='inventario_almacen_1_idx'),
        ),
    ]
