#!/usr/bin/env python3
"""
Script para crear automáticamente las migraciones merge que faltan.
Basado en la lista de migraciones que existen en producción.
"""

import os
from datetime import datetime

# Directorio de migraciones
MIGRATIONS_DIR = 'inventario/migrations'

# Migraciones merge que existen en producción pero faltan en desarrollo
MISSING_MIGRATIONS = {
    '0038_merge_20260103_2137': {
        'dependencies': [
            ('inventario', '0038_merge_20260103_2058'),
            ('inventario', '0039_logsistema'),
        ],
        'date': '2026-01-04 03:37',
    },
    '0041_merge_20260104_0027': {
        'dependencies': [
            ('inventario', '0038_merge_20260103_2137'),
            ('inventario', '0039_logsistema'),
            ('inventario', '0040_limpiar_menu_duplicados'),
        ],
        'date': '2026-01-04 06:27',
    },
}

MIGRATION_TEMPLATE = '''# Generated by Django 4.2.16 on {date}

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = {dependencies}

    operations = [
    ]
'''


def create_migration(name, dependencies, date):
    """Crea un archivo de migración."""
    filename = f'{MIGRATIONS_DIR}/{name}.py'
    
    # Verificar si ya existe
    if os.path.exists(filename):
        print(f'⚠️  {filename} ya existe, saltando...')
        return False
    
    # Formatear dependencias
    deps_str = '[\n'
    for app, migration in dependencies:
        deps_str += f"        ('{app}', '{migration}'),\n"
    deps_str += '    ]'
    
    # Crear contenido
    content = MIGRATION_TEMPLATE.format(
        date=date,
        dependencies=deps_str
    )
    
    # Escribir archivo
    with open(filename, 'w') as f:
        f.write(content)
    
    print(f'✓ Creado: {filename}')
    return True


def main():
    print('=' * 60)
    print('Creando migraciones merge que faltan...')
    print('=' * 60)
    
    # Crear directorio si no existe
    os.makedirs(MIGRATIONS_DIR, exist_ok=True)
    
    created = 0
    for name, config in MISSING_MIGRATIONS.items():
        if create_migration(name, config['dependencies'], config['date']):
            created += 1
    
    print('=' * 60)
    print(f'✓ {created} migraciones creadas exitosamente')
    print('=' * 60)
    print()
    print('Próximos pasos:')
    print('1. git add inventario/migrations/')
    print('2. git commit -m "Agregar migraciones merge que faltaban"')
    print('3. git push origin main')
    print('4. En desarrollo/calidad: git pull origin main')
    print('5. En desarrollo/calidad: docker exec -it inventario_dev python manage.py migrate')


if __name__ == '__main__':
    main()
